---

- name: merge systemd journald configuration between defaults and custom
  ansible.builtin.set_fact:
    systemd_journald: "{{ systemd_defaults_journald | combine(systemd_journald, recursive=True) }}"

- name: create systemd journald configuration
  ansible.builtin.template:
    src: systemd/journald.conf.j2
    dest: /etc/systemd/journald.conf
    mode: 0644
    owner: root
    group: root

...
