---

- name: merge systemd logind configuration between defaults and custom
  ansible.builtin.set_fact:
    systemd_logind: "{{ systemd_defaults_logind | combine(systemd_logind, recursive=True) }}"

- name: create systemd logind configuration
  ansible.builtin.template:
    src: systemd/logind.conf.j2
    dest: /etc/systemd/logind.conf
    mode: 0644
    owner: root
    group: root

...
