---

- name: merge systemd user configuration between defaults and custom
  ansible.builtin.set_fact:
    systemd_user: "{{ systemd_defaults_user | combine(systemd_user, recursive=True) }}"

- name: create systemd user configuration
  ansible.builtin.template:
    src: systemd/user.conf.j2
    dest: /etc/systemd/user.conf
    mode: 0644
    owner: root
    group: root

...
