---

systemd_unit:
  - name: vaultwarden
    state: absent
    unit_type: service
    overwrite: false
    unit_file:
      description: |
        #
        #
        #
        #
        #
        #

      Unit:
        Description: Vaultwarden API server
        Documentation: https://github.com/dani-garcia/vaultwarden
        After: network.target

      Service:
        Type: simple
        User: vaultwarden
        Group: vaultwarden
        LimitNOFILE: 1048576
        UMask: "0077"

        ExecStart: /usr/bin/vaultwarden
        EnvironmentFile: /etc/vaultwarden/config.env

        Restart: on-failure
        RestartSec: 15s

        CapabilityBoundingSet: CAP_NET_BIND_SERVICE
        AmbientCapabilities: CAP_NET_BIND_SERVICE

        LockPersonality: true
        MemoryDenyWriteExecute: true
        PrivateDevices: true
        PrivateTmp: true
        ProtectClock: true
        ProtectControlGroups: true
        ProtectHome: true
        ProtectHostname: true
        ProtectKernelLogs: true
        ProtectKernelModules: true
        ProtectKernelTunables: true
        ProtectSystem: strict
        RemoveIPC: true
        RestrictAddressFamilies: AF_UNIX AF_INET AF_INET6
        RestrictNamespaces: true
        RestrictRealtime: true
        RestrictSUIDSGID: true

        NoNewPrivileges: true

        SystemCallFilter:
          - "@system-service"
          - "~@privileged @resources"
        SystemCallArchitectures: native

        WorkingDirectory: /var/lib/vaultwarden
        ReadWriteDirectories: /var/lib/vaultwarden
        # ReadWriteDirectories: {{ vaultwarden_config.logging.log_file | dirname }}
        # {% if vaultwarden_config.web_vault.enabled is defined and
        #       vaultwarden_config.web_vault.enabled | string | length > 0 and
        #       vaultwarden_config.web_vault.enabled | bool == True %}
        # ReadWriteDirectories: {{ vaultwarden_config.directories.web_vault }}/web-vault
        # {% endif %}

      Install:
        WantedBy: multi-user.target

...
