---

systemd_unit:
  - name: "getty@tty1"
    unit_type: service
    overwrite: true
    drop_ins:
      - name: autologin
        service:
          exec_start: unsafe!
            - "-/sbin/agetty -o '-p -f -- \\u' --noclear --autologin username %I $TERM"
          type: simple

      - name: noclear
        service:
          TTYVTDisallocate: false
  # - name: chronyd
  #   unit_type: service
  #   overwrite: false
  #   unit:
  #     Description: "NTP client/server"
  #     Documentation: "man:chronyd(8) man:chrony.conf(5)"
  #     After:
  #       - ntpdate.service
  #       - sntp.service
  #       - ntpd.service
  #     Conflicts:
  #       - ntpd.service
  #       - systemd-timesyncd.service
  #     ConditionCapability:
  #       - CAP_SYS_TIME
  #   service:
  #     Type: forking
  #     PIDFile: /run/chrony/chronyd.pid
  #     EnvironmentFile:
  #       - "-/etc/sysconfig/chronyd"
  #     ExecStart:
  #       - "/usr/bin/chronyd $OPTIONS"
  #
  #     CapabilityBoundingSet:
  #       - CAP_AUDIT_CONTROL
  #       - CAP_AUDIT_READ
  #       - CAP_AUDIT_WRITE
  #       - CAP_BLOCK_SUSPEND
  #       - CAP_KILL
  #       - CAP_LEASE
  #       - CAP_LINUX_IMMUTABLE
  #       - CAP_MAC_ADMIN
  #       - CAP_MAC_OVERRIDE
  #       - CAP_MKNOD
  #       - CAP_SYS_ADMIN
  #       - CAP_SYS_BOOT
  #       - CAP_SYS_CHROOT
  #       - CAP_SYS_MODULE
  #       - CAP_SYS_PACCT
  #       - CAP_SYS_PTRACE
  #       - CAP_SYS_RAWIO
  #       - CAP_SYS_TTY_CONFIG
  #       - CAP_WAKE_ALARM
  #     DeviceAllow:
  #       - char-pps rw
  #       - char-ptp rw
  #       - char-rtc rw
  #     DevicePolicy: closed
  #     LockPersonality: true
  #     MemoryDenyWriteExecute: true
  #     NoNewPrivileges: true
  #     PrivateTmp: true
  #     ProtectControlGroups: true
  #     ProtectHome: true
  #     ProtectHostname: true
  #     ProtectKernelLogs: true
  #     ProtectKernelModules: true
  #     ProtectKernelTunables: true
  #     ProtectProc: invisible
  #     ProtectSystem: strict
  #     ReadWritePaths:
  #       - /run
  #       - /var/lib/chrony
  #       - -/var/log
  #     RestrictAddressFamilies:
  #       - AF_INET
  #       - AF_INET6
  #       - AF_UNIX
  #     RestrictNamespaces: true
  #     RestrictSUIDSGID: true
  #     SystemCallArchitectures: native
  #     SystemCallFilter:
  #       - "@cpu-emulation"
  #       - "@debug"
  #       - "@module"
  #       - "@mount"
  #       - "@obsolete"
  #       - "@raw-io"
  #       - "@reboot"
  #       - "@swap"
  #
  #     # Adjust restrictions for /usr/bin/sendmail (mailonchange directive)
  #     # NoNewPrivileges: false
  #     # ReadWritePaths:
  #     #   - -/var/spool
  #     # RestrictAddressFamilies:
  #     #   - AF_NETLINK
  #
  #   install:
  #     WantedBy: multi-user.target
...
