---

systemd_defaults_oomd:
  swap_used_limit: ""                             # 90%
  default_memory_pressure_limit: ""               # 60%
  default_memory_pressure_durationSec: ""         # 30s

...
