---

- name: merge systemd pstore configuration between defaults and custom
  ansible.builtin.set_fact:
    systemd_pstore: "{{ systemd_defaults_pstore | combine(systemd_pstore, recursive=True) }}"

- name: create systemd pstore configuration
  ansible.builtin.template:
    src: systemd/pstore.conf.j2
    dest: /etc/systemd/pstore.conf
    mode: 0644
    owner: root
    group: root

...
