---

- name: merge systemd homed configuration between defaults and custom
  ansible.builtin.set_fact:
    systemd_homed: "{{ systemd_defaults_homed | combine(systemd_homed, recursive=True) }}"

- name: create systemd homed configuration
  ansible.builtin.template:
    src: systemd/homed.conf.j2
    dest: /etc/systemd/homed.conf
    mode: 0644
    owner: root
    group: root

...
