---

- name: merge systemd networkd configuration between defaults and custom
  ansible.builtin.set_fact:
    systemd_networkd: "{{ systemd_defaults_networkd | combine(systemd_networkd, recursive=True) }}"

- name: create systemd networkd configuration
  ansible.builtin.template:
    src: systemd/networkd.conf.j2
    dest: /etc/systemd/networkd.conf
    mode: 0644
    owner: root
    group: root

...
