#!/usr/bin/python3
# -*- coding: utf-8 -*-

# (c) 2020-2026, Bodo Schulz <bodo@boone-schulz.de>
# Apache-2.0 (see LICENSE or https://opensource.org/license/apache-2-0)
# SPDX-License-Identifier: Apache-2.0

from __future__ import absolute_import, division, print_function

from typing import Any, Dict, List, Optional


class NetworkdRenderer:
    """
    Pure helpers that turn a profile dict into systemd-style INI text.

    Stateless; grouped as a class for namespacing and unit-testability.
    """

    @classmethod
    def render(
        cls,
        config: Dict[str, Any],
        description: Optional[str],
    ) -> str:
        """
        Render a profile dict into a systemd-networkd INI string.

        Section values may be a single dict or a list of dicts. List-of-dicts
        results in multiple ``[Section]`` blocks (e.g. several ``[Address]``).

        :param config: Mapping of section name to option dict / list of dicts.
        :param description: Optional free-form comment placed near the top.
        :returns: Fully rendered file content (terminated with a newline).
        """
        lines: List[str] = ["# Generated by Ansible - do not edit manually."]

        if description:
            lines.append("")
            lines.append(cls._normalize_comment(description))

        for section, payload in config.items():
            blocks: List[Dict[str, Any]] = cls._coerce_section(section, payload)
            for block in blocks:
                lines.append("")
                lines.append(f"[{section}]")
                for option, value in (block or {}).items():
                    lines.extend(cls._render_option(option, value))

        return "\n".join(lines).rstrip() + "\n"

    @staticmethod
    def _coerce_section(section: str, payload: Any) -> List[Dict[str, Any]]:
        """
        Normalize a section payload into a list of dict blocks.

        :param section: Section name (only used for error messages).
        :param payload: Either a dict, a list of dicts, or None.
        :returns: List of dicts. Empty for ``None``.
        :raises ValueError: If payload has an unsupported shape.
        """
        if payload is None:
            return []
        if isinstance(payload, dict):
            return [payload]
        if isinstance(payload, list):
            for entry in payload:
                if not isinstance(entry, dict):
                    raise ValueError(
                        f"section [{section}] list entries must be dicts, "
                        f"got {type(entry).__name__}"
                    )
            return list(payload)
        raise ValueError(
            f"section [{section}] must be dict or list of dicts, "
            f"got {type(payload).__name__}"
        )

    @classmethod
    def _render_option(cls, option: str, value: Any) -> List[str]:
        """
        Render a single ``Key=Value`` line, or repeated lines for lists.

        - ``None`` skips the key entirely.
        - Empty string ``""`` produces ``Key=`` (reset semantics).
        - ``list``/``tuple`` produces one ``Key=Value`` per element.

        :param option: The option key.
        :param value: Scalar, list of scalars, ``""`` or ``None``.
        :returns: Zero or more rendered lines.
        """
        if value is None:
            return []
        if isinstance(value, (list, tuple)):
            out: List[str] = []
            for item in value:
                if item is None:
                    continue
                out.append(f"{option}={cls._render_scalar(item)}")
            return out
        return [f"{option}={cls._render_scalar(value)}"]

    @staticmethod
    def _render_scalar(value: Any) -> str:
        """
        Convert a single value to its systemd-networkd representation.

        :param value: Raw value (bool, int, str, ...).
        :returns: String form suitable for an INI value field.
        """
        if isinstance(value, bool):
            return "true" if value else "false"
        return str(value)

    @staticmethod
    def _normalize_comment(text: str) -> str:
        """
        Ensure every line of ``text`` starts with ``#``.

        :param text: Raw description (multi-line allowed).
        :returns: A valid comment block.
        """
        out: List[str] = []
        for raw in text.splitlines():
            stripped = raw.rstrip()
            if not stripped.strip():
                out.append("#")
            elif stripped.lstrip().startswith("#"):
                out.append(stripped)
            else:
                out.append(f"# {stripped}")
        return "\n".join(out)
